### ISSUE TITLE
Outline the roadmap for the pipeline

### ISSUE THREAD

**Issue by abhi18av** [mtb-bioinformatics/MycoVarP-nf#1]
Base paper: https://www.frontiersin.org/articles/10.3389/fbinf.2021.805338/full

The source code is available upon request 🙃

**Comment by abhi18av** [comment]
Initiating roadmap:

- [x] @jloubser to share the link to source code
- [ ] @Ankita-1211 to initiate outlining the modules (similar to module design [MTBseq-nf](https://github.com/mtb-bioinformatics/MTBseq-nf/tree/master/modules/mtbseq) )
- [ ] @Ankita-1211 to sketch-out the main workflow

**Comment by justicengom** [comment]
This task will be taken over by @justicengom and @abhi18av - the goal is to create granular roadmap for the pipeline.

An investment of 20-30 minutes in every 1/2 days should be enough to complete the pipeline.


(Commented by Abhinav from my username)

**Comment by abhi18av** [comment]
Notes from our meeting on 06-04-2023 (Shared on SUN teams as well)

MycovarP-nf https://github.com/mtb-bioinformatics/MycoVarP-nf/issues/1#issuecomment-1498703590

- [x] Abhinav to create a small roadmap
- [x] Abhinav to create the nf-core template
- [ ] Justice to read that paper again and try setup the pipeline on Khaos 
- [ ] Justice Experiment with the pipeline on Khaos with standard dataset 
- [ ] Justice outline on paper the design of mycovarp-nf (in terms of modules/subworkflows) https://github.com/mtb-bioinformatics/MycoVarP-nf/issues/2 

I have initiated a project for this pipeline here https://github.com/orgs/mtb-bioinformatics/projects/4/views/1?layout=board
